import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request';

const graph = new GraphQLClient('https://api-us-east-1.hygraph.com/v2/clbogk62k0d0x01uq8rcf36i8/master')

const QUERY = gql`
    {
      posts{
        title,
        datePublished,
        slug,
        content{
          html
        }
      
      }
      authors{
        name
      }
    }
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        
        
        
      </main>
    </>
  )
}
